/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja_fuerte.edvinreyes;

import com.pe.logica.logica;
import com.pe.logica.operacion;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author User
 */
public class caja411 extends javax.swing.JFrame {

    /**
     * Creates new form caja4
     */
    private double saldo =200;
    DecimalFormat df =new DecimalFormat("###.##");
    operacion ob1 = new operacion("DEPOSITO","400","15 febrero 2021","8:00");
    operacion ob2 = new operacion("RETIRO","300","15 febrero 2021","9:10");
    operacion ob3 = new operacion("DEPOSITO","100","15 febrero 2021","14:00");
    logica banco = new logica();
    
    public caja411() {
        initComponents();
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color (18,18,18));
        jTable1.getTableHeader().setForeground(new Color (255,255,254));
        banco.addRow(ob1);
        banco.addRow(ob2);
        banco.addRow(ob3);
        banco.crearTabla(jTable1);
        JButton [] btns={btnA, btnB, btnA1};
        for (JButton btn: btns){
            btn.setUI(new BasicButtonUI());
            btn.setBackground(new Color(16,16,16));
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color (50, 30, 150));
                    
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(16,16,16));
                    
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnA1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtMonto1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtDia1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        txtMes1 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        txtHora1 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        txtMinutos1 = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        jPanel57 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        txtMonto2 = new javax.swing.JTextField();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        txtDia2 = new javax.swing.JTextField();
        jPanel66 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jPanel69 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        txtMes2 = new javax.swing.JTextField();
        jPanel71 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        txtHora2 = new javax.swing.JTextField();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel80 = new javax.swing.JPanel();
        txtMinutos2 = new javax.swing.JTextField();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        btnB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPnl.setBackground(new java.awt.Color(60, 60, 60));
        rootPnl.setPreferredSize(new java.awt.Dimension(1000, 500));
        rootPnl.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 400));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel5.setBackground(new java.awt.Color(25, 25, 25));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(25, 25, 25));
        jPanel31.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel14.setBackground(new java.awt.Color(25, 25, 25));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("    SALDO ACTUAL");
        jLabel14.setPreferredSize(new java.awt.Dimension(180, 15));
        jPanel31.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jLabel16.setBackground(new java.awt.Color(204, 51, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 255, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("1600.00");
        jPanel31.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel33.setBackground(new java.awt.Color(25, 25, 25));
        jPanel33.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel33.setLayout(new java.awt.GridLayout(4, 0));

        jLabel17.setBackground(new java.awt.Color(25, 25, 25));
        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setPreferredSize(new java.awt.Dimension(180, 15));
        jPanel33.add(jLabel17);

        jLabel18.setBackground(new java.awt.Color(25, 25, 25));
        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setPreferredSize(new java.awt.Dimension(180, 15));
        jPanel33.add(jLabel18);

        jLabel19.setBackground(new java.awt.Color(25, 25, 25));
        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setPreferredSize(new java.awt.Dimension(180, 15));
        jPanel33.add(jLabel19);

        btnA1.setBackground(new java.awt.Color(39, 39, 39));
        btnA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnA1.setForeground(new java.awt.Color(255, 102, 102));
        btnA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        btnA1.setText("SALIR\n");
        btnA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnA1MouseClicked(evt);
            }
        });
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });
        jPanel33.add(btnA1);

        jPanel5.add(jPanel33, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(25, 25, 25));
        jPanel6.setLayout(new java.awt.GridLayout(7, 0, 0, 5));

        jLabel1.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEPÓSITO");
        jPanel6.add(jLabel1);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(25, 25, 25));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(25, 25, 25));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("    MONTO");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        txtMonto1.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMonto1.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMonto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto1ActionPerformed(evt);
            }
        });
        jPanel8.add(txtMonto1, java.awt.BorderLayout.PAGE_END);

        jPanel10.setBackground(new java.awt.Color(25, 25, 25));
        jPanel10.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(25, 25, 25));
        jPanel9.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel4);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(25, 25, 25));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(25, 25, 25));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("    DÎA");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        txtDia1.setMinimumSize(new java.awt.Dimension(4, 50));
        txtDia1.setPreferredSize(new java.awt.Dimension(55, 35));
        txtDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDia1ActionPerformed(evt);
            }
        });
        jPanel13.add(txtDia1, java.awt.BorderLayout.PAGE_END);

        jPanel14.setBackground(new java.awt.Color(25, 25, 25));
        jPanel14.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(25, 25, 25));
        jPanel15.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel11);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(25, 25, 25));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(25, 25, 25));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("    MES");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel17.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel17, java.awt.BorderLayout.LINE_START);

        jPanel18.setLayout(new java.awt.BorderLayout());

        txtMes1.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMes1.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMes1ActionPerformed(evt);
            }
        });
        jPanel18.add(txtMes1, java.awt.BorderLayout.PAGE_END);

        jPanel19.setBackground(new java.awt.Color(25, 25, 25));
        jPanel19.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel16.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel20.setBackground(new java.awt.Color(25, 25, 25));
        jPanel20.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel20, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel16);

        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(25, 25, 25));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(25, 25, 25));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("    HORA");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel22.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setLayout(new java.awt.BorderLayout());

        txtHora1.setMinimumSize(new java.awt.Dimension(4, 50));
        txtHora1.setPreferredSize(new java.awt.Dimension(55, 35));
        txtHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHora1ActionPerformed(evt);
            }
        });
        jPanel23.add(txtHora1, java.awt.BorderLayout.PAGE_END);

        jPanel24.setBackground(new java.awt.Color(25, 25, 25));
        jPanel24.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel24, java.awt.BorderLayout.PAGE_START);

        jPanel21.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel25.setBackground(new java.awt.Color(25, 25, 25));
        jPanel25.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel25, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel21);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(25, 25, 25));
        jPanel27.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(25, 25, 25));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("    MINUTOS");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel27.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel27, java.awt.BorderLayout.LINE_START);

        jPanel28.setLayout(new java.awt.BorderLayout());

        txtMinutos1.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMinutos1.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMinutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutos1ActionPerformed(evt);
            }
        });
        jPanel28.add(txtMinutos1, java.awt.BorderLayout.PAGE_END);

        jPanel29.setBackground(new java.awt.Color(25, 25, 25));
        jPanel29.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel28.add(jPanel29, java.awt.BorderLayout.PAGE_START);

        jPanel26.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel30.setBackground(new java.awt.Color(25, 25, 25));
        jPanel30.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel30, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel26);

        btnA.setBackground(new java.awt.Color(39, 39, 39));
        btnA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnA.setForeground(new java.awt.Color(102, 255, 102));
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check.png"))); // NOI18N
        btnA.setText("ACEPTAR");
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
        });
        jPanel6.add(btnA);

        jPanel1.add(jPanel6);

        jPanel57.setBackground(new java.awt.Color(25, 25, 25));
        jPanel57.setLayout(new java.awt.GridLayout(7, 0, 0, 5));

        jLabel2.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RETIRO");
        jPanel57.add(jLabel2);

        jPanel58.setLayout(new java.awt.BorderLayout());

        jPanel59.setBackground(new java.awt.Color(25, 25, 25));
        jPanel59.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel59.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(25, 25, 25));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    MONTO");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel59.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel58.add(jPanel59, java.awt.BorderLayout.LINE_START);

        jPanel60.setLayout(new java.awt.BorderLayout());

        txtMonto2.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMonto2.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMonto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto2ActionPerformed(evt);
            }
        });
        jPanel60.add(txtMonto2, java.awt.BorderLayout.PAGE_END);

        jPanel61.setBackground(new java.awt.Color(25, 25, 25));
        jPanel61.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel60.add(jPanel61, java.awt.BorderLayout.PAGE_START);

        jPanel58.add(jPanel60, java.awt.BorderLayout.CENTER);

        jPanel62.setBackground(new java.awt.Color(25, 25, 25));
        jPanel62.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel62Layout = new javax.swing.GroupLayout(jPanel62);
        jPanel62.setLayout(jPanel62Layout);
        jPanel62Layout.setHorizontalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel62Layout.setVerticalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel58.add(jPanel62, java.awt.BorderLayout.LINE_END);

        jPanel57.add(jPanel58);

        jPanel63.setBackground(new java.awt.Color(25, 25, 25));
        jPanel63.setLayout(new java.awt.BorderLayout());

        jPanel64.setBackground(new java.awt.Color(25, 25, 25));
        jPanel64.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel64.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(25, 25, 25));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("    DÎA");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel64.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel63.add(jPanel64, java.awt.BorderLayout.LINE_START);

        jPanel65.setLayout(new java.awt.BorderLayout());

        txtDia2.setMinimumSize(new java.awt.Dimension(4, 50));
        txtDia2.setPreferredSize(new java.awt.Dimension(55, 35));
        txtDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDia2ActionPerformed(evt);
            }
        });
        jPanel65.add(txtDia2, java.awt.BorderLayout.PAGE_END);

        jPanel66.setBackground(new java.awt.Color(25, 25, 25));
        jPanel66.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel65.add(jPanel66, java.awt.BorderLayout.PAGE_START);

        jPanel63.add(jPanel65, java.awt.BorderLayout.CENTER);

        jPanel67.setBackground(new java.awt.Color(25, 25, 25));
        jPanel67.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel67Layout = new javax.swing.GroupLayout(jPanel67);
        jPanel67.setLayout(jPanel67Layout);
        jPanel67Layout.setHorizontalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel67Layout.setVerticalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel63.add(jPanel67, java.awt.BorderLayout.LINE_END);

        jPanel57.add(jPanel63);

        jPanel68.setLayout(new java.awt.BorderLayout());

        jPanel69.setBackground(new java.awt.Color(25, 25, 25));
        jPanel69.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel69.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(25, 25, 25));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("    MES");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel69.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel68.add(jPanel69, java.awt.BorderLayout.LINE_START);

        jPanel70.setLayout(new java.awt.BorderLayout());

        txtMes2.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMes2.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMes2ActionPerformed(evt);
            }
        });
        jPanel70.add(txtMes2, java.awt.BorderLayout.PAGE_END);

        jPanel71.setBackground(new java.awt.Color(25, 25, 25));
        jPanel71.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel70.add(jPanel71, java.awt.BorderLayout.PAGE_START);

        jPanel68.add(jPanel70, java.awt.BorderLayout.CENTER);

        jPanel72.setBackground(new java.awt.Color(25, 25, 25));
        jPanel72.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel68.add(jPanel72, java.awt.BorderLayout.LINE_END);

        jPanel57.add(jPanel68);

        jPanel73.setLayout(new java.awt.BorderLayout());

        jPanel74.setBackground(new java.awt.Color(25, 25, 25));
        jPanel74.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel74.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(25, 25, 25));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("    HORA");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel74.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel73.add(jPanel74, java.awt.BorderLayout.LINE_START);

        jPanel75.setLayout(new java.awt.BorderLayout());

        txtHora2.setMinimumSize(new java.awt.Dimension(4, 50));
        txtHora2.setPreferredSize(new java.awt.Dimension(55, 35));
        txtHora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHora2ActionPerformed(evt);
            }
        });
        jPanel75.add(txtHora2, java.awt.BorderLayout.PAGE_END);

        jPanel76.setBackground(new java.awt.Color(25, 25, 25));
        jPanel76.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel76Layout = new javax.swing.GroupLayout(jPanel76);
        jPanel76.setLayout(jPanel76Layout);
        jPanel76Layout.setHorizontalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel76Layout.setVerticalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel75.add(jPanel76, java.awt.BorderLayout.PAGE_START);

        jPanel73.add(jPanel75, java.awt.BorderLayout.CENTER);

        jPanel77.setBackground(new java.awt.Color(25, 25, 25));
        jPanel77.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel77Layout = new javax.swing.GroupLayout(jPanel77);
        jPanel77.setLayout(jPanel77Layout);
        jPanel77Layout.setHorizontalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel77Layout.setVerticalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel73.add(jPanel77, java.awt.BorderLayout.LINE_END);

        jPanel57.add(jPanel73);

        jPanel78.setLayout(new java.awt.BorderLayout());

        jPanel79.setBackground(new java.awt.Color(25, 25, 25));
        jPanel79.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel79.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(25, 25, 25));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("    MINUTOS");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel79.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel78.add(jPanel79, java.awt.BorderLayout.LINE_START);

        jPanel80.setLayout(new java.awt.BorderLayout());

        txtMinutos2.setMinimumSize(new java.awt.Dimension(4, 50));
        txtMinutos2.setPreferredSize(new java.awt.Dimension(55, 35));
        txtMinutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutos2ActionPerformed(evt);
            }
        });
        jPanel80.add(txtMinutos2, java.awt.BorderLayout.PAGE_END);

        jPanel81.setBackground(new java.awt.Color(25, 25, 25));
        jPanel81.setPreferredSize(new java.awt.Dimension(164, 50));

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel80.add(jPanel81, java.awt.BorderLayout.PAGE_START);

        jPanel78.add(jPanel80, java.awt.BorderLayout.CENTER);

        jPanel82.setBackground(new java.awt.Color(25, 25, 25));
        jPanel82.setPreferredSize(new java.awt.Dimension(40, 80));

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel78.add(jPanel82, java.awt.BorderLayout.LINE_END);

        jPanel57.add(jPanel78);

        btnB.setBackground(new java.awt.Color(39, 39, 39));
        btnB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnB.setForeground(new java.awt.Color(102, 255, 102));
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check.png"))); // NOI18N
        btnB.setText("ACEPTAR");
        btnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMouseClicked(evt);
            }
        });
        jPanel57.add(btnB);

        jPanel1.add(jPanel57);

        rootPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(60, 60, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        rootPnl.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(rootPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMonto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto1ActionPerformed

    private void txtDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDia1ActionPerformed

    private void txtMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes1ActionPerformed

    private void txtHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHora1ActionPerformed

    private void txtMinutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutos1ActionPerformed

    private void txtMonto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto2ActionPerformed

    private void txtDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDia2ActionPerformed

    private void txtMes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMes2ActionPerformed

    private void txtHora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHora2ActionPerformed

    private void txtMinutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutos2ActionPerformed

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
        // TODO add your handling code here:
        
        
        banco.addRow(new operacion("DEPÓSITO",txtMonto1.getText(),txtDia1.getText()+" "+
                txtMes1.getText()+" 2021",txtHora1.getText()+":"+txtMinutos1.getText()));
        banco.crearTabla(jTable1);
        double monto=Double.parseDouble(txtMonto1.getText());
        saldo=saldo+monto;
        jLabel16.setText(df.format(saldo));
        
        
        
    }//GEN-LAST:event_btnAMouseClicked

    private void btnBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseClicked
        // TODO add your handling code here:
        banco.addRow(new operacion("RETIRO",txtMonto2.getText(),txtDia2.getText()+" "+
                txtMes2.getText()+" 2021",txtHora2.getText()+":"+txtMinutos2.getText()));
        banco.crearTabla(jTable1);
        double monto=Double.parseDouble(txtMonto2.getText());
        saldo=saldo-monto;
        jLabel16.setText(df.format(saldo));
    }//GEN-LAST:event_btnBMouseClicked

    private void btnA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnA1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_btnA1MouseClicked

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caja411.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caja411.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caja411.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caja411.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caja411().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel rootPnl;
    private javax.swing.JTextField txtDia1;
    private javax.swing.JTextField txtDia2;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    private javax.swing.JTextField txtMes1;
    private javax.swing.JTextField txtMes2;
    private javax.swing.JTextField txtMinutos1;
    private javax.swing.JTextField txtMinutos2;
    private javax.swing.JTextField txtMonto1;
    private javax.swing.JTextField txtMonto2;
    // End of variables declaration//GEN-END:variables
}
