/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja_fuerte.edvinreyes;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class caja1 extends javax.swing.JFrame {
public static  int num=0;
    public ArrayList<dinero> pisto = new ArrayList();
    public ArrayList<Historial> his = new ArrayList();
    int ide;
    dinero ob1 = new dinero(ide);
    public int d1 = 1000;
    public caja1() {

        initComponents();
        this.setLocationRelativeTo(null);

        Boton_Gupo.add(selec1);
        Boton_Gupo.add(selec2);
        Boton_Gupo.add(selec3);
        Boton_Gupo.add(selec4);
        Boton_Gupo.add(selec5);
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Boton_Gupo = new javax.swing.ButtonGroup();
        selec6 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selec1 = new javax.swing.JRadioButton();
        selec2 = new javax.swing.JRadioButton();
        selec3 = new javax.swing.JRadioButton();
        selec4 = new javax.swing.JRadioButton();
        selec5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Text3 = new javax.swing.JTextField();
        Boton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        boton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        text8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text9 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        selec6.setText("Deposito");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Cerrar caja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 543, -1, -1));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 543, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Escoja una de las opciones\n"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 37, -1, 31));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("  Opciones de caja fuerte");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 6, 191, 29));

        selec1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selec1.setText("Ver dinero");
        getContentPane().add(selec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, -1, -1));

        selec2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selec2.setText("Deposito");
        selec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec2ActionPerformed(evt);
            }
        });
        getContentPane().add(selec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 86, -1, -1));

        selec3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selec3.setText("Retiro");
        selec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec3ActionPerformed(evt);
            }
        });
        getContentPane().add(selec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 86, -1, -1));

        selec4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selec4.setText("Historial");
        selec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec4ActionPerformed(evt);
            }
        });
        getContentPane().add(selec4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 397, -1, -1));

        selec5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selec5.setText("Cambiar Pin");
        getContentPane().add(selec5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Porfavor llene los datos que se le solicitan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 116, -1, -1));

        text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 158, 221, 25));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Ingrese el dinero a depositar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 137, 221, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Escriba su nuevo pin de acceso");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 279, -1, 24));

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 309, 175, 25));

        Boton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Boton1.setText("Aceptar");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 393, -1, -1));

        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText("Aceptar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 108, 70, 27));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dia", "Mes", "Año", "Hora", "Hora"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 425, 461, 112));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Ingrese el dinero a depositar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 186, 221, -1));

        text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 207, 221, 25));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Ingrese el mes en que hace el deposito\n");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 237, -1, -1));

        text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 258, 221, 25));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("ingrese la hora");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 289, 221, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("ingrese los minutos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 341, 145, -1));

        text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 310, 221, 25));

        text5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 362, 221, 25));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Porfavor llene los datos que se le solicitan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 116, -1, -1));

        text6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 158, 221, 25));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Ingrese el dinero a depositar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 137, 221, -1));

        boton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton2.setText("Aceptar");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 393, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Ingrese el dinero a depositar");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 186, 221, -1));

        text7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 207, 221, 25));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Ingrese el mes en que hace el deposito\n");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 237, -1, -1));

        text8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 258, 221, 25));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("ingrese la hora");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 289, 221, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("ingrese los minutos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 341, 145, -1));

        text9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 221, 25));

        text10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 362, 221, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicio co = new Inicio();
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int año=0;
        Historial a = new Historial("1","12",año," 5","12");
        Historial b = new Historial("3","6 ",año,"10","24");
        Historial c = new Historial("8","3 ",año,"11","35");
        his.add(a);
        his.add(b);
        his.add(c);
          
        if (selec4.isSelected()){
        if(num==0){
        jTable1.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel asd=(DefaultTableModel) jTable1.getModel();
        Object[] filas = new Object[asd.getColumnCount()]; 
        
       
        for (int i = 0; i < his.size(); i++) {
            if(asd.getRowCount()>10){

            }else{
            filas[0]=his.get(i).getDia();
            filas[1]=his.get(i).getMes();
            filas[2]=his.get(i).getAño();
            filas[3]=his.get(i).getHora();
            filas[4]=his.get(i).getMin();
            asd.addRow(filas);
            }

        }     
        num=1;
        his.clear();
        }
         }else{
             
             
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void selec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selec4ActionPerformed

    private void selec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selec3ActionPerformed

    private void selec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selec2ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        if (selec2.isSelected()) {
          
        }
    }//GEN-LAST:event_Boton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
        if (selec1.isSelected()) {
                jLabel1.setText(jLabel1.getText()+d1);
            } else if(selec1.isSelected()==false){                
                jLabel1.setText("");
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caja1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.ButtonGroup Boton_Gupo;
    private javax.swing.JTextField Text3;
    private javax.swing.JButton boton2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton selec1;
    private javax.swing.JRadioButton selec2;
    private javax.swing.JRadioButton selec3;
    private javax.swing.JRadioButton selec4;
    private javax.swing.JRadioButton selec5;
    private javax.swing.JRadioButton selec6;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text9;
    // End of variables declaration//GEN-END:variables
}
