/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja_fuerte.edvinreyes;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JFrame {

    public static ArrayList pin = new ArrayList();
    public static ArrayList pin1 = new ArrayList();
    public static ArrayList pin2 = new ArrayList();

    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);

        pin.add("1234");
        pin1.add("5678");
        pin2.add("2019");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseña = new javax.swing.JPasswordField();
        bonton1 = new javax.swing.JButton();
        bonton2 = new javax.swing.JButton();
        bonton3 = new javax.swing.JButton();
        bonton4 = new javax.swing.JButton();
        bonton5 = new javax.swing.JButton();
        bonton6 = new javax.swing.JButton();
        bonton7 = new javax.swing.JButton();
        bonton8 = new javax.swing.JButton();
        bonton9 = new javax.swing.JButton();
        bonton10 = new javax.swing.JButton();
        bonton11 = new javax.swing.JButton();
        bonton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pren = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        contraseña.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        bonton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton1.setText("1");
        bonton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton1ActionPerformed(evt);
            }
        });

        bonton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton2.setText("2");
        bonton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton2ActionPerformed(evt);
            }
        });

        bonton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton3.setText("3");
        bonton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton3ActionPerformed(evt);
            }
        });

        bonton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton4.setText("4");
        bonton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton4ActionPerformed(evt);
            }
        });

        bonton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton5.setText("5");
        bonton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton5ActionPerformed(evt);
            }
        });

        bonton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton6.setText("6");
        bonton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton6ActionPerformed(evt);
            }
        });

        bonton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton7.setText("7");
        bonton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton7ActionPerformed(evt);
            }
        });

        bonton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton8.setText("8");
        bonton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton8ActionPerformed(evt);
            }
        });

        bonton9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton9.setText("9");
        bonton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton9ActionPerformed(evt);
            }
        });

        bonton10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton10.setText("*");
        bonton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton10ActionPerformed(evt);
            }
        });

        bonton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton11.setText("0");
        bonton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton11ActionPerformed(evt);
            }
        });

        bonton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bonton12.setText("#");
        bonton12.setToolTipText("");
        bonton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton12ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese su PIN de acceso");

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pren.setText("A");
        pren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pren)
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bonton10)
                        .addGap(18, 18, 18)
                        .addComponent(bonton11)
                        .addGap(18, 18, 18)
                        .addComponent(bonton12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bonton4)
                            .addGap(18, 18, 18)
                            .addComponent(bonton5)
                            .addGap(18, 18, 18)
                            .addComponent(bonton6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bonton1)
                            .addGap(18, 18, 18)
                            .addComponent(bonton2)
                            .addGap(18, 18, 18)
                            .addComponent(bonton3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bonton7)
                            .addGap(18, 18, 18)
                            .addComponent(bonton8)
                            .addGap(18, 18, 18)
                            .addComponent(bonton9))))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pren))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton1)
                    .addComponent(bonton2)
                    .addComponent(bonton3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton4)
                    .addComponent(bonton5)
                    .addComponent(bonton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton7)
                    .addComponent(bonton8)
                    .addComponent(bonton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton10)
                    .addComponent(bonton11)
                    .addComponent(bonton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed

        int a = 0;
        if (pren.isSelected()) {
            caja1 co = new caja1();
            co.setVisible(true);
            this.setVisible(false);
        } else {
            if (contraseña.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "No ingreso datos", "Datos erroneos", JOptionPane.QUESTION_MESSAGE);
                a = 2;
            } else {
                for (int i = 0; i < pin.size(); i++) {
                    if (contraseña.getText().equals(pin.get(i))) {
                        caja1 co = new caja1();
                        co.setVisible(true);
                        this.setVisible(false);
                        a = 1;
                    }
                }
                for (int i = 0; i < pin1.size(); i++) {
                    if (contraseña.getText().equals(pin1.get(i))) {
                        caja2 co = new caja2();
                        co.setVisible(true);
                        this.setVisible(false);
                        a = 1;
                    }
                }
                for (int i = 0; i < pin2.size(); i++) {
                    if (contraseña.getText().equals(pin2.get(i))) {
                        caja3 co = new caja3();
                        co.setVisible(true);
                        this.setVisible(false);
                        a = 1;
                    }
                }
            }
            
            if (a == 0) {
                JOptionPane.showMessageDialog(null, "Datos incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
                contraseña.setText("");
            }
        }


    }//GEN-LAST:event_siguienteActionPerformed

    private void bonton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton1ActionPerformed
        contraseña.setText(contraseña.getText() + "1");
    }//GEN-LAST:event_bonton1ActionPerformed

    private void bonton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton2ActionPerformed
        contraseña.setText(contraseña.getText() + "2");
    }//GEN-LAST:event_bonton2ActionPerformed

    private void bonton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton3ActionPerformed
        contraseña.setText(contraseña.getText() + "3");
    }//GEN-LAST:event_bonton3ActionPerformed

    private void bonton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton4ActionPerformed
        contraseña.setText(contraseña.getText() + "4");
    }//GEN-LAST:event_bonton4ActionPerformed

    private void bonton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton5ActionPerformed
        contraseña.setText(contraseña.getText() + "5");
    }//GEN-LAST:event_bonton5ActionPerformed

    private void bonton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton6ActionPerformed
        contraseña.setText(contraseña.getText() + "6");
    }//GEN-LAST:event_bonton6ActionPerformed

    private void bonton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton7ActionPerformed
        contraseña.setText(contraseña.getText() + "7");
    }//GEN-LAST:event_bonton7ActionPerformed

    private void bonton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton8ActionPerformed
        contraseña.setText(contraseña.getText() + "8");
    }//GEN-LAST:event_bonton8ActionPerformed

    private void bonton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton9ActionPerformed
        contraseña.setText(contraseña.getText() + "9");
    }//GEN-LAST:event_bonton9ActionPerformed

    private void bonton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton10ActionPerformed
        contraseña.setText(contraseña.getText() + "*");
    }//GEN-LAST:event_bonton10ActionPerformed

    private void bonton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton11ActionPerformed
        contraseña.setText(contraseña.getText() + "0");
    }//GEN-LAST:event_bonton11ActionPerformed

    private void bonton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton12ActionPerformed
        contraseña.setText(contraseña.getText() + "#");
    }//GEN-LAST:event_bonton12ActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void prenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bonton1;
    private javax.swing.JButton bonton10;
    private javax.swing.JButton bonton11;
    private javax.swing.JButton bonton12;
    private javax.swing.JButton bonton2;
    private javax.swing.JButton bonton3;
    private javax.swing.JButton bonton4;
    private javax.swing.JButton bonton5;
    private javax.swing.JButton bonton6;
    private javax.swing.JButton bonton7;
    private javax.swing.JButton bonton8;
    private javax.swing.JButton bonton9;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton pren;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
